global:
  monitoring:
    batch: true
    traces:
      enabled: true
      mode: grpc
      exporter: otlp
      endpoint: otel-collector-opentelemetry-collector.formance.svc.cluster.local
      port: 4317
      insecure: true
    logs:
      format: ""
image:
  pullPolicy: Always

debug: true

server:
  address: ""
  tls:
    enabled: true
    insecureSkipVerify: true

agent:
  id: "dev-public-region"
  baseUrl: ""
  production: false
  # Authentication token
  authentication:
    mode: token
    token: abcd
